export const dummyIssues = [
  {
    id: 1,
    title: "Pothole on Main Road",
    description: "Large pothole causing traffic near market area.",
    address: "Main Street, Near City Market",
    category: "Road Maintenance",
    status: "pending",
    assigned_department: "Public Works Department",
    createdAt: "2025-09-29T10:00:00Z",
    photo_url: "https://picsum.photos/400/200?random=1",
    ai_classification: "Road Damage",
    ai_priority_score: 0.85,
  },
  {
    id: 2,
    title: "Streetlight not working",
    description: "Streetlight flickers and stays off most of the night.",
    address: "5th Avenue, Near Park",
    category: "Electrical",
    status: "inprogress",
    assigned_department: "Electrical Department",
    createdAt: "2025-09-25T09:00:00Z",
    photo_url: "https://picsum.photos/400/200?random=2",
    ai_classification: "Lighting Issue",
    ai_priority_score: 0.62,
  },
  {
    id: 3,
    title: "Garbage pile-up",
    description: "Uncollected garbage causing bad odor and flies.",
    address: "Sector 14, Near Temple",
    category: "Sanitation",
    status: "resolved",
    assigned_department: "Sanitation Department",
    createdAt: "2025-09-20T12:00:00Z",
    resolved_at: "2025-09-28T16:00:00Z",
    photo_url: "https://picsum.photos/400/200?random=3",
    ai_classification: "Waste Management",
    ai_priority_score: 0.72,
    citizen_rating: 4,
    citizen_feedback: "Cleaned well, but took some time.",
  },
];
