export const dummyIssues = [
  {
    issue_id: 1,
    title: "Pothole on 5th Street",
    description: "Large pothole causing traffic issues",
    status: "pending",
    category: "pothole",
    priority: "high",
    address: "5th Street, NY",
    latitude: 40.7589,
    longitude: -73.9851,
    reporter_name: "John Doe",
    createdAt: "2025-10-10T10:30:00Z",
    is_anonymous: false,
  },
  {
    issue_id: 2,
    title: "Broken streetlight",
    description: "Streetlight not working near park",
    status: "inprogress",
    category: "streetlight",
    priority: "medium",
    address: "Central Park, NY",
    latitude: 40.7812,
    longitude: -73.9665,
    reporter_name: "Anonymous",
    createdAt: "2025-10-09T08:15:00Z",
    is_anonymous: true,
  },
  {
    issue_id: 3,
    title: "Garbage not collected",
    description: "Overflowing garbage bin",
    status: "resolved",
    category: "garbage",
    priority: "low",
    address: "Madison Ave, NY",
    latitude: 40.7736,
    longitude: -73.9566,
    reporter_name: "Alice Smith",
    createdAt: "2025-10-08T12:00:00Z",
    is_anonymous: false,
  },
  // Add more dummy issues as needed
];
